// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioMetaInfo`

class PhotoMetaInfo {
  final String? make;
  final String? model;
  final String? capture;
  final double? latitude;
  final double? longitude;

  const PhotoMetaInfo({
    this.make,
    this.model,
    this.capture,
    this.latitude,
    this.longitude,
  });

  @override
  int get hashCode =>
      make.hashCode ^
      model.hashCode ^
      capture.hashCode ^
      latitude.hashCode ^
      longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhotoMetaInfo &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          capture == other.capture &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

class RFileInfo {
  final String id;
  final String name;
  final String ext;
  final String parent;
  final PlatformInt64 createTime;
  final PlatformInt64 modifyTime;
  final PlatformInt64 accessTime;
  final BigInt size;

  const RFileInfo({
    required this.id,
    required this.name,
    required this.ext,
    required this.parent,
    required this.createTime,
    required this.modifyTime,
    required this.accessTime,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ext.hashCode ^
      parent.hashCode ^
      createTime.hashCode ^
      modifyTime.hashCode ^
      accessTime.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RFileInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ext == other.ext &&
          parent == other.parent &&
          createTime == other.createTime &&
          modifyTime == other.modifyTime &&
          accessTime == other.accessTime &&
          size == other.size;
}
