// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'file_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 验证日期字符串是否有效
/// 过滤掉像 ":  :     :  : " 这样的无效格式，但保留包含"上午"或"下午"的有效日期
Future<bool> isValidDate({required String dateStr}) =>
    RustLib.instance.api.crateApiFileMetaIsValidDate(dateStr: dateStr);

/// 处理EXIF日期字符串，转换为标准格式
/// 输入格式: "2020:03:10 18:56:08"
/// 输出格式: "2020-03-10T18:56:08"
/// 处理失败时返回: "0000-01-01T00:00:00"
Future<String> formatDate({required String dateStr}) =>
    RustLib.instance.api.crateApiFileMetaFormatDate(dateStr: dateStr);

AudioMetaInfo getAudioMetaInfo({required String filePath}) =>
    RustLib.instance.api.crateApiFileMetaGetAudioMetaInfo(filePath: filePath);

RustImageSize getImageSize({required String imagePath}) =>
    RustLib.instance.api.crateApiFileMetaGetImageSize(imagePath: imagePath);

VideoMetaInfo getVideoMetaInfo({required String videoPath}) =>
    RustLib.instance.api.crateApiFileMetaGetVideoMetaInfo(videoPath: videoPath);
