// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'file_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_date`, `is_valid_date`

PhotoMetaInfo getImageMetaInfo({required String imagePath}) =>
    RustLib.instance.api.crateApiFileMetaGetImageMetaInfo(imagePath: imagePath);

AudioMetaInfo getAudioMetaInfo({required String filePath}) =>
    RustLib.instance.api.crateApiFileMetaGetAudioMetaInfo(filePath: filePath);

PsdMetaInfo getPsdMetaInfo({required String psdPath}) =>
    RustLib.instance.api.crateApiFileMetaGetPsdMetaInfo(psdPath: psdPath);

VideoMetaInfo getVideoMetaInfo({required String videoPath}) =>
    RustLib.instance.api.crateApiFileMetaGetVideoMetaInfo(videoPath: videoPath);
