// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioMetaInfo {
  final String title;
  final String artist;
  final String album;
  final String year;

  const AudioMetaInfo({
    required this.title,
    required this.artist,
    required this.album,
    required this.year,
  });

  @override
  int get hashCode =>
      title.hashCode ^ artist.hashCode ^ album.hashCode ^ year.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetaInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          year == other.year;
}

class PhotoMetaInfo {
  final String? make;
  final String? model;
  final String? capture;
  final double? latitude;
  final double? longitude;

  const PhotoMetaInfo({
    this.make,
    this.model,
    this.capture,
    this.latitude,
    this.longitude,
  });

  @override
  int get hashCode =>
      make.hashCode ^
      model.hashCode ^
      capture.hashCode ^
      latitude.hashCode ^
      longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhotoMetaInfo &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          capture == other.capture &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

class PsdMetaInfo {
  final int width;
  final int height;

  const PsdMetaInfo({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PsdMetaInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class RFileInfo {
  final String id;
  final String name;
  final String ext;
  final String parent;
  final PlatformInt64 createTime;
  final PlatformInt64 modifyTime;
  final PlatformInt64 accessTime;
  final BigInt size;
  final bool isDir;

  const RFileInfo({
    required this.id,
    required this.name,
    required this.ext,
    required this.parent,
    required this.createTime,
    required this.modifyTime,
    required this.accessTime,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ext.hashCode ^
      parent.hashCode ^
      createTime.hashCode ^
      modifyTime.hashCode ^
      accessTime.hashCode ^
      size.hashCode ^
      isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RFileInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ext == other.ext &&
          parent == other.parent &&
          createTime == other.createTime &&
          modifyTime == other.modifyTime &&
          accessTime == other.accessTime &&
          size == other.size &&
          isDir == other.isDir;
}

class VideoMetaInfo {
  final int width;
  final int height;
  final String make;
  final String model;
  final String capture;

  const VideoMetaInfo({
    required this.width,
    required this.height,
    required this.make,
    required this.model,
    required this.capture,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      make.hashCode ^
      model.hashCode ^
      capture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoMetaInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          make == other.make &&
          model == other.model &&
          capture == other.capture;
}
