// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_info`, `get_audio_info`, `get_file_type`, `get_image_info`, `get_video_info`

List<FileInfo> sortFileInfoByPaths({
  required List<String> paths,
  required List<FileInfo> fileInfoList,
}) => RustLib.instance.api.crateApiFileInfoSortFileInfoByPaths(
  paths: paths,
  fileInfoList: fileInfoList,
);

String generateId() => RustLib.instance.api.crateApiFileInfoGenerateId();

Stream<FileInfo> getListStreamPool({required List<String> paths}) =>
    RustLib.instance.api.crateApiFileInfoGetListStreamPool(paths: paths);

Stream<FileInfo> getListStream({required List<String> paths}) =>
    RustLib.instance.api.crateApiFileInfoGetListStream(paths: paths);

List<FileInfo> getListPool({required List<String> paths}) =>
    RustLib.instance.api.crateApiFileInfoGetListPool(paths: paths);

List<FileInfo> getList({required List<String> paths}) =>
    RustLib.instance.api.crateApiFileInfoGetList(paths: paths);

Future<DateTime?> parseStrDatetime({required String s}) =>
    RustLib.instance.api.crateApiFileInfoParseStrDatetime(s: s);

DateInfo? getDateInfo({DateTime? date}) =>
    RustLib.instance.api.crateApiFileInfoGetDateInfo(date: date);
