// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_in_china`, `parse_gps_string`, `transform_lat`, `transform_lon`, `wgs84_to_gcj02`

/// 解析GPS坐标并转换为高德地图坐标(GCJ-02)
Future<(double, double)?> parseAndConvertGps({
  required String latStr,
  required String latRef,
  required String lonStr,
  required String lonRef,
}) => RustLib.instance.api.crateApiGpsInfoParseAndConvertGps(
  latStr: latStr,
  latRef: latRef,
  lonStr: lonStr,
  lonRef: lonRef,
);
