// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `transform_lat`, `transform_lon`

/// 判断坐标是否在中国大陆境内
Future<bool> isInChina({required double lat, required double lon}) =>
    RustLib.instance.api.crateApiGpsInfoIsInChina(lat: lat, lon: lon);

/// 将WGS84坐标转换为火星坐标(GCJ-02)
Future<(double, double)> wgs84ToGcj02({
  required double wgsLat,
  required double wgsLon,
}) => RustLib.instance.api.crateApiGpsInfoWgs84ToGcj02(
  wgsLat: wgsLat,
  wgsLon: wgsLon,
);
