// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_in_china`, `parse_gps_coordinates`, `parse_urational_coordinate`, `transform_lat`, `transform_lon`, `wgs84_to_gcj02`

Future<CameraInfo?> getImageMetaInfo({required String imagePath}) =>
    RustLib.instance.api.crateApiImgExifGetImageMetaInfo(imagePath: imagePath);

class CameraInfo {
  final String? make;
  final String? model;
  final String? capture;
  final double? latitude;
  final double? longitude;

  const CameraInfo({
    this.make,
    this.model,
    this.capture,
    this.latitude,
    this.longitude,
  });

  @override
  int get hashCode =>
      make.hashCode ^
      model.hashCode ^
      capture.hashCode ^
      latitude.hashCode ^
      longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraInfo &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          capture == other.capture &&
          latitude == other.latitude &&
          longitude == other.longitude;
}
