// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_log_dir`, `get_log_path`, `write_log_to_file`

/// 写入错误日志
/// 调试模式：打印到控制台
/// 发布模式：写入日志文件
Future<void> writeError({required String message}) =>
    RustLib.instance.api.crateApiLogWriteError(message: message);

/// 写入警告日志
/// 调试模式：打印到控制台
/// 发布模式：写入日志文件
Future<void> writeWarning({required String message}) =>
    RustLib.instance.api.crateApiLogWriteWarning(message: message);

/// 写入信息日志
/// 调试模式：打印到控制台
/// 发布模式：写入日志文件
Future<void> writeInfo({required String message}) =>
    RustLib.instance.api.crateApiLogWriteInfo(message: message);
