// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_date`, `parse_svg_length`

/// 验证日期字符串是否有效
/// 过滤掉像 ":  :     :  : " 这样的无效格式，但保留包含"上午"或"下午"的有效日期
Future<bool> isValidDate({required String dateStr}) =>
    RustLib.instance.api.crateApiMetaInfoIsValidDate(dateStr: dateStr);

Future<AudioMetaInfo> getAudioMetaInfo({required String filePath}) =>
    RustLib.instance.api.crateApiMetaInfoGetAudioMetaInfo(filePath: filePath);

Future<Resolution?> getImageSize({
  required String imagePath,
  required String ext,
}) => RustLib.instance.api.crateApiMetaInfoGetImageSize(
  imagePath: imagePath,
  ext: ext,
);

Future<Resolution?> getSvgSize({required String svgPath}) =>
    RustLib.instance.api.crateApiMetaInfoGetSvgSize(svgPath: svgPath);

Future<VideoMetaInfo> getVideoMetaInfo({required String videoPath}) =>
    RustLib.instance.api.crateApiMetaInfoGetVideoMetaInfo(videoPath: videoPath);
