// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AudioMetaInfo {
  final String title;
  final String artist;
  final String album;
  final String year;

  const AudioMetaInfo({
    required this.title,
    required this.artist,
    required this.album,
    required this.year,
  });

  @override
  int get hashCode =>
      title.hashCode ^ artist.hashCode ^ album.hashCode ^ year.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetaInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          year == other.year;
}

class BaseInfo {
  final String name;
  final String ext;
  final String parent;
  final DateTime? create;
  final DateTime modify;
  final DateTime access;
  final int size;
  final bool isDir;

  const BaseInfo({
    required this.name,
    required this.ext,
    required this.parent,
    this.create,
    required this.modify,
    required this.access,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      ext.hashCode ^
      parent.hashCode ^
      create.hashCode ^
      modify.hashCode ^
      access.hashCode ^
      size.hashCode ^
      isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BaseInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ext == other.ext &&
          parent == other.parent &&
          create == other.create &&
          modify == other.modify &&
          access == other.access &&
          size == other.size &&
          isDir == other.isDir;
}

class DateInfo {
  final DateTime date;
  final List<String> weekday;

  const DateInfo({required this.date, required this.weekday});

  @override
  int get hashCode => date.hashCode ^ weekday.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DateInfo &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          weekday == other.weekday;
}

class FileInfo {
  final String id;
  String name;
  String newName;
  String parent;
  String path;
  String tempPath;
  final String beforePath;
  String ext;
  String newExt;
  DateInfo? created;
  DateInfo? modified;
  DateInfo? accessed;
  FileType fileType;
  final Resolution? resolution;
  final FileMetaInfo? metaInfo;
  Uint8List? thumbnail;
  final int size;
  String group;
  bool checked;

  FileInfo({
    required this.id,
    required this.name,
    required this.newName,
    required this.parent,
    required this.path,
    required this.tempPath,
    required this.beforePath,
    required this.ext,
    required this.newExt,
    this.created,
    this.modified,
    this.accessed,
    required this.fileType,
    this.resolution,
    this.metaInfo,
    this.thumbnail,
    required this.size,
    required this.group,
    required this.checked,
  });

  String fullNewName() =>
      RustLib.instance.api.crateApiModelsFileInfoFullNewName(that: this);

  String fullOldName() =>
      RustLib.instance.api.crateApiModelsFileInfoFullOldName(that: this);

  bool isDir() => RustLib.instance.api.crateApiModelsFileInfoIsDir(that: this);

  String newPath({required bool isUndo}) => RustLib.instance.api
      .crateApiModelsFileInfoNewPath(that: this, isUndo: isUndo);

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      newName.hashCode ^
      parent.hashCode ^
      path.hashCode ^
      tempPath.hashCode ^
      beforePath.hashCode ^
      ext.hashCode ^
      newExt.hashCode ^
      created.hashCode ^
      modified.hashCode ^
      accessed.hashCode ^
      fileType.hashCode ^
      resolution.hashCode ^
      metaInfo.hashCode ^
      thumbnail.hashCode ^
      size.hashCode ^
      group.hashCode ^
      checked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          newName == other.newName &&
          parent == other.parent &&
          path == other.path &&
          tempPath == other.tempPath &&
          beforePath == other.beforePath &&
          ext == other.ext &&
          newExt == other.newExt &&
          created == other.created &&
          modified == other.modified &&
          accessed == other.accessed &&
          fileType == other.fileType &&
          resolution == other.resolution &&
          metaInfo == other.metaInfo &&
          thumbnail == other.thumbnail &&
          size == other.size &&
          group == other.group &&
          checked == other.checked;
}

class FileMetaInfo {
  final String title;
  final String artist;
  final String album;
  final String year;
  final DateInfo? capture;
  final String make;
  final String model;
  final double? longitude;
  final double? latitude;
  final String location;

  const FileMetaInfo({
    required this.title,
    required this.artist,
    required this.album,
    required this.year,
    this.capture,
    required this.make,
    required this.model,
    this.longitude,
    this.latitude,
    required this.location,
  });

  static Future<FileMetaInfo> default_() =>
      RustLib.instance.api.crateApiModelsFileMetaInfoDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      year.hashCode ^
      capture.hashCode ^
      make.hashCode ^
      model.hashCode ^
      longitude.hashCode ^
      latitude.hashCode ^
      location.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileMetaInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          year == other.year &&
          capture == other.capture &&
          make == other.make &&
          model == other.model &&
          longitude == other.longitude &&
          latitude == other.latitude &&
          location == other.location;
}

enum FileType { image, video, audio, doc, archive, folder, other }

class PhotoMetaInfo {
  final String? make;
  final String? model;
  final DateTime? capture;
  final double? latitude;
  final double? longitude;

  const PhotoMetaInfo({
    this.make,
    this.model,
    this.capture,
    this.latitude,
    this.longitude,
  });

  @override
  int get hashCode =>
      make.hashCode ^
      model.hashCode ^
      capture.hashCode ^
      latitude.hashCode ^
      longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhotoMetaInfo &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          capture == other.capture &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

class Resolution {
  final int width;
  final int height;

  const Resolution({required this.width, required this.height});

  static Future<Resolution> default_() =>
      RustLib.instance.api.crateApiModelsResolutionDefault();

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Resolution &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class VideoMetaInfo {
  final int width;
  final int height;
  final String make;
  final String model;
  final DateTime? capture;

  const VideoMetaInfo({
    required this.width,
    required this.height,
    required this.make,
    required this.model,
    this.capture,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      make.hashCode ^
      model.hashCode ^
      capture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoMetaInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          make == other.make &&
          model == other.model &&
          capture == other.capture;
}
