// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String simplifiedToTraditional({required String text}) =>
    RustLib.instance.api.crateApiSimpleSimplifiedToTraditional(text: text);

String traditionalToSimplified({required String text}) =>
    RustLib.instance.api.crateApiSimpleTraditionalToSimplified(text: text);

Future<String?> deleteToTrash({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleDeleteToTrash(filePath: filePath);

Future<String?> deleteAllToTrash({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiSimpleDeleteAllToTrash(filePaths: filePaths);

Future<CameraInfo?> getImageMetaInfo({required String imagePath}) =>
    RustLib.instance.api.crateApiSimpleGetImageMetaInfo(imagePath: imagePath);

/// 照片元信息结构体
class CameraInfo {
  final String? make;
  final String? model;
  final String? capture;

  const CameraInfo({
    this.make,
    this.model,
    this.capture,
  });

  @override
  int get hashCode => make.hashCode ^ model.hashCode ^ capture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraInfo &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          capture == other.capture;
}
