// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String?> getImageCaptureDate({required String imagePath}) => RustLib
    .instance
    .api
    .crateApiSimpleGetImageCaptureDate(imagePath: imagePath);

String simplifiedToTraditional({required String text}) =>
    RustLib.instance.api.crateApiSimpleSimplifiedToTraditional(text: text);

String traditionalToSimplified({required String text}) =>
    RustLib.instance.api.crateApiSimpleTraditionalToSimplified(text: text);

Future<String?> deleteToTrash({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleDeleteToTrash(filePath: filePath);

Future<String?> deleteAllToTrash({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiSimpleDeleteAllToTrash(filePaths: filePaths);
